"""Deterministic mock inference service for Phase 3.

Produces a synthetic segmentation from image geometry.
Does NOT load any PyTorch model, checkpoint, or trained weights.

The synthetic mask is:
- obviously geometric (centered ellipsoid)
- deterministic (same input → same output)
- fast (CPU-only, no heavy computation)
- explicitly labeled as MOCK / non-clinical

Labels are generated internally as {0, 1, 2, 3} and exported
to BraTS-compatible {0, 1, 2, 4} via the centralized
`to_brats_labels` function.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import nibabel as nib
import numpy as np

from app.core.constants import (
    BRATS_ET,
    BRATS_NCR,
    BRATS_ED,
    INTERNAL_BACKGROUND,
    INTERNAL_ED,
    INTERNAL_ET,
    INTERNAL_NCR,
    REGION_NAMES,
    REQUIRED_MODALITIES,
    to_brats_labels,
)
from app.inference.base import InferenceResult

logger = logging.getLogger(__name__)

_MOCK_MODEL_INFO_MESSAGE = (
    "No trained checkpoint is registered. Mock inference is available for "
    "pipeline validation. Headline Dice/HD95 metrics are not available."
)


class MockInferenceService:
    """Deterministic synthetic inference for pipeline validation.

    This service conforms to the InferenceService protocol.
    It does NOT perform real tumor detection.
    """

    # Provenance, read by the API through app.inference.base's accessors.
    # `model_loaded` stays False: no checkpoint is ever loaded here, and
    # /health must never claim otherwise.
    inference_source = "mock"
    synthetic = True
    model_loaded = False
    available = True
    model_version = None

    def describe(self) -> dict[str, object]:
        return {
            "inference_source": self.inference_source,
            "model_loaded": False,
            "model_version": None,
            "checkpoint_id": None,
            "message": _MOCK_MODEL_INFO_MESSAGE,
        }

    def predict(
        self,
        case_dir: Path,
        output_dir: Path,
        case_id: str,
        *,
        has_ground_truth: bool = False,
    ) -> InferenceResult:
        """Generate a deterministic synthetic segmentation.

        1. Read stored NIfTI inputs and validate modalities.
        2. Produce a centered ellipsoidal synthetic mask.
        3. Remap internal labels to BraTS format (3 → 4).
        4. Save as NIfTI, preserving the reference affine/header.
        5. Compute deterministic geometric measurements.
        6. Return structured InferenceResult.
        """
        logger.info(
            "mock_inference_started",
            extra={"case_id": case_id, "inference_source": "mock"},
        )

        # 1. Validate modalities exist
        reference_path = self._validate_modalities(case_dir, case_id)

        # 2. Load reference volume for shape/affine
        reference_img = nib.load(str(reference_path))
        reference_data = np.asanyarray(reference_img.dataobj)
        reference_data = np.squeeze(reference_data)
        shape = reference_data.shape
        affine = np.asarray(reference_img.affine, dtype=np.float64)
        spacing = tuple(float(z) for z in reference_img.header.get_zooms()[:3])

        # 3. Generate deterministic synthetic segmentation
        internal_mask = self._generate_synthetic_mask(shape)

        # 4. Remap to BraTS labels (single centralized conversion)
        brats_mask = to_brats_labels(internal_mask)

        # 5. Save output
        output_dir.mkdir(parents=True, exist_ok=True)
        seg_filename = "segmentation.nii.gz"
        seg_path = output_dir / seg_filename
        seg_img = nib.Nifti1Image(brats_mask.astype(np.int16), affine)
        seg_img.header.set_zooms(spacing)
        nib.save(seg_img, str(seg_path))

        # Measurements and metrics are computed centrally in job_queue.py
        # after the segmentation artifact is generated.

        # 7. Build metadata
        metadata = {
            "inference_source": "mock",
            "model_version": None,
            "preprocessing_version": None,
            "input_modalities": list(REQUIRED_MODALITIES),
            "inference_timestamp": datetime.now(timezone.utc).isoformat(),
            "input_shape": list(int(s) for s in shape),
            "input_spacing": list(spacing),
            "has_ground_truth": has_ground_truth,
            "evaluation_metrics": "not_available" if has_ground_truth else None,
            "synthetic": True,
            "description": (
                "Synthetic segmentation generated by MockInferenceService. "
                "Not derived from a trained medical model. "
                "Not a medical prediction."
            ),
        }

        # 8. Write result metadata
        result_meta_path = output_dir / "result.json"
        result_meta_path.write_text(
            json.dumps(metadata, indent=2, default=str),
            encoding="utf-8",
        )

        logger.info(
            "mock_inference_completed",
            extra={
                "case_id": case_id,
                "inference_source": "mock",
                "output_shape": list(int(s) for s in brats_mask.shape),
            },
        )

        return InferenceResult(
            segmentation_path=seg_filename,
            metadata=metadata,
        )

    def _validate_modalities(self, case_dir: Path, case_id: str) -> Path:
        """Verify that all required modality files exist. Return first found path."""
        reference_path: Path | None = None
        for modality in REQUIRED_MODALITIES:
            # Check for both .nii.gz and .nii
            found = False
            for ext in (".nii.gz", ".nii"):
                candidate = case_dir / f"{modality}{ext}"
                if candidate.is_file():
                    found = True
                    if reference_path is None:
                        reference_path = candidate
                    break
            if not found:
                raise RuntimeError(
                    f"Expected modality file for '{modality}' not found in case directory. "
                    f"Case: {case_id}"
                )
        assert reference_path is not None
        return reference_path

    def _generate_synthetic_mask(self, shape: tuple[int, ...]) -> np.ndarray:
        """Create a deterministic centered ellipsoidal synthetic segmentation.

        The mask uses three concentric ellipsoidal shells:
        - Outermost: ED (label 2) — edema
        - Middle:    NCR (label 1) — necrotic core
        - Inner:     ET (label 3, internal) — enhancing tumor

        The ellipsoid is centered in the volume with radii proportional
        to each axis dimension. This is obviously geometric and cannot
        be confused with a real tumor prediction.
        """
        mask = np.zeros(shape, dtype=np.int16)
        center = np.array([s / 2.0 for s in shape])

        # Radii as fractions of each axis dimension
        # ED: 20% of each axis
        # NCR: 12% of each axis
        # ET: 6% of each axis
        radii_ed = np.array([s * 0.20 for s in shape])
        radii_ncr = np.array([s * 0.12 for s in shape])
        radii_et = np.array([s * 0.06 for s in shape])

        # Create coordinate grids
        coords = np.mgrid[tuple(slice(0, s) for s in shape)]
        # Normalized distance from center for each axis
        dist_sq = sum(
            ((coords[i] - center[i]) / max(radii_ed[i], 1e-6)) ** 2
            for i in range(len(shape))
        )

        # Build shells from outside in
        mask[dist_sq <= 1.0] = INTERNAL_ED

        dist_ncr = sum(
            ((coords[i] - center[i]) / max(radii_ncr[i], 1e-6)) ** 2
            for i in range(len(shape))
        )
        mask[dist_ncr <= 1.0] = INTERNAL_NCR

        dist_et = sum(
            ((coords[i] - center[i]) / max(radii_et[i], 1e-6)) ** 2
            for i in range(len(shape))
        )
        mask[dist_et <= 1.0] = INTERNAL_ET

        return mask

