import { TestTube2 } from "lucide-react";

export function ViewerDisclaimer() {
  return (
    <div className="rounded-lg border border-amber-400/30 bg-amber-50 p-4">
      <div className="flex gap-3">
        <div className="flex-shrink-0">
          <TestTube2 className="h-5 w-5 text-amber-600" />
        </div>
        <div className="space-y-1">
          <h3 className="text-sm font-semibold text-amber-800">
            Synthetic Demo Mode
          </h3>
          <p className="text-xs leading-relaxed text-amber-700">
            The displayed segmentation was generated by a deterministic mock
            inference service. It is not produced by a trained clinical model and
            must not be interpreted as a medical diagnosis.
          </p>
        </div>
      </div>
    </div>
  );
}
